services:
  - type: web
    name: ni-engineering-backend
    env: docker
    dockerfilePath: backend/Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://manage.niengineeringbd.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
